
import { getStageMultiplier } from '../model/stages.js'
import { assertEquals, assertFalse, assertNotNull, assertThrows, assertTrue } from './assert.js'

describe('getStageMultiplier', () => {
  it('should get attack stage multipliers', () => {
    assertEquals(getStageMultiplier('attack', -6), 1/4)
    assertEquals(getStageMultiplier('attack', -5), 2/7)
    assertEquals(getStageMultiplier('attack', -4), 1/3)
    assertEquals(getStageMultiplier('attack', -3), 2/5)
    assertEquals(getStageMultiplier('attack', -2), 1/2)
    assertEquals(getStageMultiplier('attack', -1), 2/3)
    assertEquals(getStageMultiplier('attack', 0), 1)
    assertEquals(getStageMultiplier('attack', 1), 1.5)
    assertEquals(getStageMultiplier('attack', 2), 2)
    assertEquals(getStageMultiplier('attack', 3), 2.5)
    assertEquals(getStageMultiplier('attack', 4), 3)
    assertEquals(getStageMultiplier('attack', 5), 3.5)
    assertEquals(getStageMultiplier('attack', 6), 4)
  })
  it('should get accuracy stage multipliers', () => {
    assertEquals(getStageMultiplier('accuracy', -6), 1/3)
    assertEquals(getStageMultiplier('accuracy', -5), 3/8)
    assertEquals(getStageMultiplier('accuracy', -4), 3/7)
    assertEquals(getStageMultiplier('accuracy', -3), 1/2)
    assertEquals(getStageMultiplier('accuracy', -2), 3/5)
    assertEquals(getStageMultiplier('accuracy', -1), 3/4)
    assertEquals(getStageMultiplier('accuracy', 0), 1)
    assertEquals(getStageMultiplier('accuracy', 1), 4/3)
    assertEquals(getStageMultiplier('accuracy', 2), 5/3)
    assertEquals(getStageMultiplier('accuracy', 3), 2)
    assertEquals(getStageMultiplier('accuracy', 4), 7/3)
    assertEquals(getStageMultiplier('accuracy', 5), 8/3)
    assertEquals(getStageMultiplier('accuracy', 6), 3)
  })
  it('should get evasion stage multipliers', () => {
    assertEquals(getStageMultiplier('evasion', -6), 1/3)
    assertEquals(getStageMultiplier('evasion', -5), 3/8)
    assertEquals(getStageMultiplier('evasion', -4), 3/7)
    assertEquals(getStageMultiplier('evasion', -3), 1/2)
    assertEquals(getStageMultiplier('evasion', -2), 3/5)
    assertEquals(getStageMultiplier('evasion', -1), 3/4)
    assertEquals(getStageMultiplier('evasion', 0), 1)
    assertEquals(getStageMultiplier('evasion', 1), 4/3)
    assertEquals(getStageMultiplier('evasion', 2), 5/3)
    assertEquals(getStageMultiplier('evasion', 3), 2)
    assertEquals(getStageMultiplier('evasion', 4), 7/3)
    assertEquals(getStageMultiplier('evasion', 5), 8/3)
    assertEquals(getStageMultiplier('evasion', 6), 3)
  })
})